### GET /
GET http://localhost:5001

### Register a user POST /auth/register
POST http://localhost:5001/auth/register
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### Login a user POST /auth/login
POST http://localhost:5001/auth/login
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### Fetch all todos GET /TODOS (protected via cookie session)
GET http://localhost:5001/todos

### Creates a new todo POST /TODOS (protected via cookie session)
POST http://localhost:5001/todos
Content-Type: application/json

{
    "task": "Finish coding the projects"
}

### Update a todo PUT /TODOS/:ID (protected via cookie session)
PUT http://localhost:5001/todos/2?page=4
Content-Type: application/json

{
    "completed": "1"
}

### Delete a todo PUT /TODOS/:ID (protected via cookie session)
DELETE  http://localhost:5001/todos/5

# Note: VS Code REST Client can preserve cookies if `rest-client.rememberCookiesForSubsequentRequests` is enabled.
